apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: econatlas
    user: econatlas
    secureJsonData:
      password: econatlas
    jsonData:
      database: econatlas
      sslmode: disable
      postgresVersion: 1600
    editable: true
